name: websockets-simple
version: 0.1.3
synopsis: Composable websockets clients
description: See README at <https://github.com/athanclark/websockets-simple#readme>
maintainer: Athan Clark <athan.clark@gmail.com>
license: BSD3
github: athanclark/websockets-simple
category: Web
extra-source-files:
  - README.md

ghc-options: -Wall

dependencies:
  - base >= 4.11 && < 5
  - aeson
  - async
  - bytestring
  - chan >= 0.0.4
  - exceptions
  - extractable-singleton >= 0.0.1
  - monad-control-aligned >= 0.0.1
  - profunctors
  - purescript-iso >= 0.0.6
  - stm
  - text
  - transformers
  - wai-transformers >= 0.1.0
  - websockets >= 0.12.4

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - websockets-simple
      - stm
      - tasty
      - tasty-hspec
      - hspec
